#!/usr/bin/env node
/**
 * openapi-emit.mjs — 最小 OpenAPI 3.1 YAML 发射器 + spec 落盘。
 *
 * 不引入第三方依赖（各 app 只有 gateway 有 yaml 包），手写确定性发射：
 * - key 按插入序输出，param 名按字母序
 * - 字符串按需加引号（JSON 双引号即合法 YAML 双引号标量）
 *
 * writeSpec(appDir, spec): 同时写 openapi.yaml 与 openapi.json。
 * app 的 /docs 路由用 createRequire 读 openapi.json（免 yaml 依赖）。
 */
import { writeFileSync } from "node:fs";
import { join } from "node:path";

const YAML_RESERVED_WORD = /^(true|false|null|~|yes|no|on|off)$/i;

function quoteIfNeeded(s) {
	if (s === "") return '""';
	if (
		s.trim() === s &&
		/^[A-Za-z0-9_][A-Za-z0-9_. \-/]*$/.test(s) &&
		!/^-/.test(s) &&
		!YAML_RESERVED_WORD.test(s) &&
		!/^\d/.test(s)
	) {
		return s;
	}
	return JSON.stringify(s);
}

function scalar(v) {
	if (v === null || v === undefined) return "null";
	if (typeof v === "boolean" || typeof v === "number") return String(v);
	return quoteIfNeeded(String(v));
}

export function toYaml(node, indent = 0) {
	const pad = "  ".repeat(indent);
	if (node === null || node === undefined) return `${pad}null`;
	if (typeof node === "boolean" || typeof node === "number")
		return `${pad}${node}`;
	if (typeof node === "string") return `${pad}${quoteIfNeeded(node)}`;
	if (Array.isArray(node)) {
		if (node.length === 0) return `${pad}[]`;
		return node
			.map((item) => {
				if (item !== null && typeof item === "object") {
					const inner = toYaml(item, indent + 1).split("\n");
					const first = inner[0].slice(pad.length + 2);
					const rest = inner.slice(1).join("\n");
					return `${pad}- ${first}${rest ? `\n${rest}` : ""}`;
				}
				return `${pad}- ${scalar(item)}`;
			})
			.join("\n");
	}
	const keys = Object.keys(node);
	if (keys.length === 0) return `${pad}{}`;
	return keys
		.map((k) => {
			const v = node[k];
			if (v !== null && typeof v === "object") {
				if (Array.isArray(v) && v.length === 0)
					return `${pad}${quoteIfNeeded(k)}: []`;
				if (!Array.isArray(v) && Object.keys(v).length === 0)
					return `${pad}${quoteIfNeeded(k)}: {}`;
				return `${pad}${quoteIfNeeded(k)}:\n${toYaml(v, indent + 1)}`;
			}
			return `${pad}${quoteIfNeeded(k)}: ${scalar(v)}`;
		})
		.join("\n");
}

const HEADER =
	"# Generated by scripts/gen-openapi.mjs — DO NOT EDIT BY HAND.\n" +
	"# 由模块扫描/路由表生成；query 参数名为静态提取（尽力而为），类型均为 string。\n";

export function writeSpec(appDir, spec) {
	const yaml = `${HEADER}${toYaml(spec)}\n`;
	writeFileSync(join(appDir, "openapi.yaml"), yaml, "utf-8");
	writeFileSync(
		join(appDir, "openapi.json"),
		`${JSON.stringify(spec, null, 2)}\n`,
		"utf-8",
	);
}

/** 通用 JSON 响应体（上游透传，结构因接口而异）。 */
export function jsonOk(description = "上游透传 JSON") {
	return {
		description,
		content: {
			"application/json": { schema: { type: "object" } },
		},
	};
}

/** 单个 query 参数。 */
export function qp(name, { required = false, description } = {}) {
	const p = {
		name,
		in: "query",
		required,
		schema: { type: "string" },
	};
	if (description) p.description = description;
	return p;
}

/** 单个 path 参数。 */
export function pp(name, { description } = {}) {
	const p = {
		name,
		in: "path",
		required: true,
		schema: { type: "string" },
	};
	if (description) p.description = description;
	return p;
}

/** 构造一个 operation。 */
export function op(summary, params = [], { description, responses } = {}) {
	const o = { summary, parameters: params };
	if (description) o.description = description;
	o.responses = responses ?? { 200: jsonOk() };
	return o;
}

/** 构造完整 spec。 */
export function makeSpec({ title, version, description, serverUrl, paths }) {
	return {
		openapi: "3.1.0",
		info: { title, version, description },
		servers: [{ url: serverUrl }],
		paths,
	};
}
